import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { BotConnection } from './bot-connection.js';
import { ToolFactory } from './tool-factory.js';
import { MessageStore } from './message-store.js';
import { registerPositionTools } from './tools/position-tools.js';
import { registerInventoryTools } from './tools/inventory-tools.js';
import { registerBlockTools } from './tools/block-tools.js';
import { registerEntityTools } from './tools/entity-tools.js';
import { registerChatTools } from './tools/chat-tools.js';
import { registerFlightTools } from './tools/flight-tools.js';
import { registerGameStateTools } from './tools/gamestate-tools.js';
import { registerCraftingTools } from './tools/crafting-tools.js';
import { registerFurnaceTools } from './tools/furnace-tools.js';
import { registerContainerTools } from './tools/container-tools.js';
import { registerObservationTools } from './tools/observation-tools.js';
import { registerPlayerActionTools } from './tools/player-action-tools.js';
import { registerNavigationTools } from './tools/navigation-tools.js';
import { registerInteractionTools } from './tools/interaction-tools.js';
import { registerCombatTools } from './tools/combat-tools.js';
import { registerTradingTools } from './tools/trading-tools.js';
import { registerUtilityTools } from './tools/utility-tools.js';

export function createMcpServer(connection: BotConnection, messageStore: MessageStore): McpServer {
  const server = new McpServer({ name: 'minecraft-mcp-server', version: '2.0.4' });
  const factory = new ToolFactory(server, connection);
  const getBot = () => connection.getBot()!;
  registerPositionTools(factory, getBot);
  registerInventoryTools(factory, getBot);
  registerBlockTools(factory, getBot);
  registerEntityTools(factory, getBot);
  registerChatTools(factory, getBot, messageStore);
  registerFlightTools(factory, getBot);
  registerGameStateTools(factory, getBot);
  registerCraftingTools(factory, getBot);
  registerFurnaceTools(factory, getBot);
  registerContainerTools(factory, getBot);
  registerObservationTools(factory, getBot);
  registerPlayerActionTools(factory, getBot);
  registerNavigationTools(factory, getBot);
  registerInteractionTools(factory, getBot);
  registerCombatTools(factory, getBot);
  registerTradingTools(factory, getBot);
  registerUtilityTools(factory, getBot);
  return server;
}
